# https://docs.docker.com/compose/compose-file/
version: '3.9'

volumes:
  node_modules: {}
  postgres_data: {}
  postgres_backups: {}
  django_ipython_data: {}
  static_volume: {}

services:
  reactjs:
    container_name: 'ai-4-smart-healthcare_reactjs'
    build:
      context: .
      dockerfile: ./compose/reactjs/Dockerfile
      args:
        - DEBUG=false
    command: /start.sh
    volumes:
      - ./front-end:/app
      - node_modules:/app/node_modules
    expose:
      - 4000

  postgres:
    env_file: ./back-end/config/.env
    container_name: "ai-4-smart-healthcare_postgres"
    image: postgres:14.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups

  django:
    env_file: ./back-end/config/.env
    container_name: "ai-4-smart-healthcare_django"
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /start.sh
    environment:
      - DEBUG=False
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    volumes:
      - ./back-end:/app
      - django_ipython_data:/root/.ipython
      - static_volume:/app/static
    links:
      - postgres
    expose:
      - 8000

  nginx:
    container_name: "ai-4-smart-healthcare_nginx"
    image: nginx:latest
    depends_on:
      - reactjs
      - django
    volumes:
      - ./compose/nginx:/etc/nginx/conf.d
      - ./nginxlogs:/var/log/nginx
      - static_volume:/app/staticfiles
    ports:
      - 8080:80
